project_name: "ford-corp"
output_dir: "data"
user_agent: "RAGScraper/1.0 (+https://example.com/contact)"
concurrency: 8
request_timeout_sec: 20
retry_attempts: 3
sleep_min_ms: 200
sleep_max_ms: 600
respect_robots: true

seed_urls:
  - "https://corporate.ford.com/operations.html"
  - "https://media.ford.com/content/fordmedia/fna/us/en/news.html"
  - "https://www.ford.com/support/"
  - "https://corporate.ford.com/company.html"
  - "https://www.ford.com/vehicles/"

# token-aware chunking (fallbacks to char-based if tiktoken unavailable)
chunk_max_tokens: 350
chunk_overlap_tokens: 40

# OpenAI embeddings
embedding_model: "text-embedding-3-small"
embedding_dimensions: 1536

# Chroma collection
collection_name: "ford-rag"
