# Add your target pages in seed_urls. Keep it explicit and realistic.
# Example placeholders below — replace with your actual pages.
project_name: "ub-campus-living"   # change anytime
output_dir: "data"
user_agent: "RAGScraper/1.0 (+https://example.com/contact)"
concurrency: 8
request_timeout_sec: 20
retry_attempts: 3
sleep_min_ms: 200
sleep_max_ms: 600
respect_robots: true

seed_urls:
  - "https://www.buffalo.edu/campus-living/policies.html"
  - "https://www.buffalo.edu/campus-living/how-to/maintenance.html"
  - "https://www.buffalo.edu/campus-living/how-to/mail-and-packages.html"
  # Add more URLs here
